package com.tc.websocket;


public enum Params {
	//default value
	WEBSOCKET_PORT,
	WEBSOCKET_PROXY_BACKEND_HOST,
	WEBSOCKET_PROXY_BACKEND_PORT,
	WEBSOCKET_REDIRECT_PORTS,
	WEBSOCKET_CERT_FILE,
	WEBSOCKET_KEY_FILE,
	WEBSOCKET_USER,
	WEBSOCKET_PASSWORD,
	WEBSOCKET_LEAK_DETECTOR,
	WEBSOCKET_NATIVE_TRANSPORT,
	WEBSOCKET_SEND_BUFFER,
	WEBSOCKET_RECEIVE_BUFFER,
	WEBSOCKET_ALLOWED_ORIGINS,
	WEBSOCKET_NATIVE_SSL,
	WEBSOCKET_PROFILED,
	WEBSOCKET_EVENT_LOOP_THREADS,
	WEBSOCKET_THREAD_COUNT,
	WEBSOCKET_PING_INTERVAL,
	WEBSOCKET_PURGE_INTERVAL,
	WEBSOCKET_COMPRESSION_ENABLED,
	WEBSOCKET_CLIENT_CACHE_MAX,
	WEBSOCKET_MAX_CONNECTIONS,
	WEBSOCKET_MAX_MSG_SIZE,
	WEBSOCKET_ENCRYPT,
	WEBSOCKET_KEYSTORE_PATH,
	WEBSOCKET_KEY_PASSWORD,
	WEBSOCKET_KEYSTORE_PASSWORD,
	WEBSOCKET_KEYSTORE_TYPE,
	WEBSOCKET_CLUSTERED,
	WEBSOCKET_CLUSTERMATE_MONITOR,
	WEBSOCKET_CLUSTERMATE_EXPIRATION,
	WEBSOCKET_BROADCAST_SERVER,
	WEBSOCKET_DEBUG,
	WEBSOCKET_ALLOW_ANONYMOUS,
	WEBSOCKET_TEST_MODE,
	WEBSOCKET_FILTER;
	
	
	

	Params(){
		
	}


}
